#Creating an array in python using numpy

In [4]:
import numpy as np
arr=np.array([3,6,5,7,9])
print(arr)

[3 6 5 7 9]


In [2]:
#Indexing
arr[0]

np.int64(3)

#printing shape of array

In [5]:
arr.shape

dtype('int64')

In [7]:
arr.dtype
arr[2]=25
print(arr)

[ 3  6 25  7  9]


#Intrinsic Numpy Array Creation

In [8]:
zero=np.zeros([2,5])
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
zero.shape

(2, 5)

In [11]:
zero.dtype

dtype('float64')

In [15]:
range=np.arange(10)
print(range)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
s=np.linspace(1,20,10)
print(s)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [19]:
e=np.empty((2,4))
print(e)

[[4.67296746e-307 1.69121096e-306 1.86921143e-306 7.56597770e-307]
 [1.42419938e-306 7.56603881e-307 8.45603440e-307 4.45046008e-307]]


In [23]:
#Printing identity matrix
imatrix=np.identity(5)
print(imatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
#Reshape the size of array
a=np.array([[2,5,1],
           [8,7,6]])
a.reshape(3,2)
print(a)

[[2 5 1]
 [8 7 6]]


In [6]:
#Makes one-dimensional array
a=np.array([[2,5,1],
           [8,7,6]])
b=a.ravel()
print(b)

[2 5 1 8 7 6]


In [47]:
#Printing the sum of array elements according to axis
arr=np.array([[2,8,7],[7 ,6,4],[3,1,5]])
s=arr.sum(axis=0)
print(s)
s=arr.sum(axis=1)
print(s)
s=arr.sum()#It returns the sum of all array elements
print(s)

[12 15 16]
[17 17  9]
43


In [8]:
#Printing transpose of the matrix
T=arr.T
print(T)

[[2 7 3]
 [8 6 1]
 [7 4 5]]


In [23]:
#Printing dimensions of matrix
arr=np.array([[2,8,7],[7 ,6,4],[3,1,5],[5,0,1]])
arr.ndim

2

In [20]:
#Gives size of an array
arr.size

12

In [21]:
#Printing total bytes consumed by an array
arr.nbytes

96

In [27]:
#Returns the index having greatest value in an array
arr=np.array([10,20,15,30,25])
arr.argmax()

np.int64(3)

In [28]:
#Returns the index having smallest value in an array
arr.argmin()

np.int64(0)

In [29]:
#Returns the indices of array by sorting it
arr.argsort()

array([0, 2, 1, 4, 3])

In [32]:
#printing the index of maximum or minimum array element of all axis 0 or 1
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.argmax(axis=0)

array([2, 2, 2])

In [33]:
arr.argmin(axis=1)

array([0, 0, 0])

In [34]:
#Print the index of sorted array
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [36]:
#Convert into one-dimensional array
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#Arithmetic operations of the array
ar1=np.array([[1,2,4],[3,5,7],[6,9,8]])
ar2=np.array([[8,5,2],[7,4,1],[3,9,6]])
ar3=ar1+ar2
print(ar3)
ar3=ar1-ar2
print(ar3)
ar3=ar1*ar2
print(ar3)
ar3=ar1/ar2
print(ar3)

[[ 9  7  6]
 [10  9  8]
 [ 9 18 14]]
[[-7 -3  2]
 [-4  1  6]
 [ 3  0  2]]
[[ 8 10  8]
 [21 20  7]
 [18 81 48]]
[[0.125      0.4        2.        ]
 [0.42857143 1.25       7.        ]
 [2.         1.         1.33333333]]


In [46]:
#Square root of an array
arr=np.array([[1,16],[4,9]])
sqrt=np.sqrt(arr)
print(sqrt)

[[1. 4.]
 [2. 3.]]


In [49]:
#Print the index of array elements according to condition
arr=np.array([[8,5,2],[7,4,1],[3,9,6]])
np.where(arr>5)

(array([0, 1, 2, 2]), array([0, 0, 1, 2]))

In [50]:
#Gives the count of elements which are greater than zero
np.count_nonzero(arr)

9

In [3]:
import sys
import numpy as np
py_ar=[0,4,55,2]
np_ar=np.array(py_ar)
sys.getsizeof(1)*len(py_ar)

112